### ISSUE TITLE
ZG conflict with TechGuns

### ISSUE THREAD

**Issue by AceSardonyx** [alphawolf918/Zollern-Galaxy#97] opened 2023-09-19 16:49 UTC
**Describe the bug**
I was shooting a mob with a gun from the TechGuns mod and crashed immediately

**Expected behavior**
i shoot gun, and gun go pew

 - MCVer[1.12.2]
 - ZGVer[2.0.45]
 - RAM[4/8GB]

I was thinking maybe view this log? lmao
https://mclo.gs/Ijon8Uf#L18900
I reported it to techguns too bc I don't know which mod is at fault
all info is in the log
worth checking out

**Comment by alphawolf918** [comment] 2023-10-05 23:11
Mod imcompatibility, not a bug. Recommend reaching out to developers of other mod. Closing issue.

**Closed by alphawolf918** 2023-10-05 23:11 UTC
Labels: bug

**Comment by AceSardonyx** [comment] 2023-10-05 23:39
I was told it was an issue with this mod and I got more reasoning as to why. Could you look into it or talk with them? All I know is something in zg thinks FlyingGibs (gore death animation entity) is an actual entity and no other mods do

**Comment by alphawolf918** [comment] 2023-10-05 23:47
No.
