### ISSUE TITLE
Initializing game error

### ISSUE THREAD

**Issue by dhgameryt** [alphawolf918/Zollern-Galaxy#75] opened 2022-01-16 00:49 UTC
[crash-2022-01-15_21.33.57-client.txt](https://github.com/alphawolf918/Zollern-Galaxy/files/7876164/crash-2022-01-15_21.33.57-client.txt)

The game crash in the initializing.
 mod version: Zollern Galaxy v1.12.2-2.0.35
 game version: forge 1.12.2 14.23.5.2960

**Comment by alphawolf918** [comment] 2022-01-16 01:10
Thanks for letting me know about this. I'm pretty sure i just need to add an if statement or modify the existing one, I'm guessing you don't have Extreme Reactors installed, because it looks like it's trying to find it, and failing. I'll take a look at this ASAP. Thank you so much.

**Comment by alphawolf918** [comment] 2022-01-16 01:59
Is there a config option in your ZollernGalaxy/core.cfg file that reads "Enable Extreme Reactors Compatibility" by any chance? If so, try turning that off. I'll be looking into this in the meantime, hopefully that "fixes" it for now, though. I'll take a more in-depth look tomorrow.

It has to do with an Induction Smelter recipe:

`// Blutonium
		if (ModHelperBase.useExtremeReactors && ConfigManagerZG.enableExtremeReactorsCompat) {
			// 8 Cyanite + 2 Enrichment Dust = 2 Blutonium Ingots
			InductionSmelterRecipes.addRecipe(20000, new ItemStack(BrItems.ingotCyanite, 9), new ItemStack(ZGItems.dustEnrichment, 2), new ItemStack(BrItems.ingotBlutonium, 2));
		}`

**Comment by alphawolf918** [comment] 2022-01-16 17:04
Hey, I searched through your crash report and couldn't find anything relating to Extreme Reactors, so I'm a bit confused as to why it would try to load anything for that mod. If you are using Extreme Reactors, what version of it are you using?

The version that the mod is built against is: **ExtremeReactors-1.12.2-0.4.5.68** for **1.12.2***.

**Comment by alphawolf918** [comment] 2022-01-16 17:14
Nevermind, think I figured it out. It's technical, but I found the reason why it was searching for a class that didn't exist (basically tried importing it in the wrong class) when Extreme Reactors was missing. So hopefully should be fixed in the next version. I'll leave this up til then.

In the meantime, you could try installing that mod with ZeroCore alongside it so that it works, but I understand if you don't want to do this.

**Comment by dhgameryt** [comment] 2022-01-16 17:16
ok, I solved the crash putting the mod extreme reactors, now I will try to disable the compatibility with that mod and remove it

**Comment by alphawolf918** [comment] 2022-01-16 17:17
Yeah, the issue is definitely on my end, so thank you again for letting me know. I should have a new build out soon.

**Comment by alphawolf918** [comment] 2022-01-16 17:26
Alright, CurseForge is being kinda funky, so I've uploaded a new build on my GitHub. You can get to it here:

https://github.com/alphawolf918/Zollern-Galaxy/releases/download/1.12.2.2.0.36/ZollernGalaxy-1.12.2-v2.0.36.jar

Let me know if this works, please.

**Comment by dhgameryt** [comment] 2022-01-16 17:53
Now it initialize without any problem even if the extreme reactors mod is not there, thanks!

**Closed** 2022-01-16 17:54 UTC
Labels: bug, awaiting feedback
